targets:
  TaskMaster:
    type: application
    platform: iOS
    sources:
      - TaskMaster
      - TaskMaster/GeneratedAssets
    dependencies:
      - package: TaskMasterPackages
    settings:
      base:
        INFOPLIST_FILE: TaskMaster/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.TaskMaster
